const $ = (element) => document.querySelector(element);
const $$ = (element) => document.querySelectorAll(element);
const nodes = {
  sections: {
    mainHeaderMobile: $(".headerMobileMain"),
    searchHeaderMobile: $(".headerMobileSearch"),
    savedCitiesHeaderMobile: $(".headerMobileSaved"),
    nextDaysHeaderMobile: $(".headerMobileNextDays"),
    mobileNav: $(".mobileNav"),
    mainWeather: $(".mainWeather"),
    weatherPerHours: $(".weatherPerHours"),
    weatherPerHoursSlider: $(".weatherPerHours__sliderWeatherHours"),
    mainSearchMobile: $(".mainSearchMobile"),
    savedCities: $(".savedCities"),
    mainInfo: $(".main"),
    mainHeaderDesktop: $(".main__header"),
    mainNext2Days: $(".mainNext2Days"),
    mainNext2DaysContent: $(".mainNext2Days__content"),
  },
  elements: {
    arroBackNextDays: $(".headerMobileNextDays__arrowBack"),
    menuIconMobile: $$(".menuIconMobile"),
    closeNavMobile: $(".mobileNav__closeMobileNav"),
    mobileMainBtn: $(".mobileNav__main"),
    mobileSearchBtn: $(".mobileNav__search"),
    mobileSavedCitiesBtn: $(".mobileNav__saved"),
    darkModeBtn: $$(".darkModeBtn"),
    cityNameHeader: $(".headerMobileMain__cityName"),
    saveCityBtn: $(".saveCityBtn"),
    searchCityInput: $(".searchCityInput"),
    sunriseInfo: $(".sunriseInfo"),
    sunsetInfo: $(".sunsetInfo"),
    dateInfo: $(".dateInfo"),
    hourInfo: $(".hourInfo"),
    temperature: $(".tempInfo"),
    typeWeatherInfo: $(".typeWeatherInfo"),
    pressure: $(".pressureInfo"),
    humadity: $(".humadityInfo"),
    windSpeed: $(".windSpeedInfo"),
    twoDaysMore: $(".twoDaysMore"),
    daymoreInfo: $(".content__city"),
    //*Elements desktop
    searchCityDesktop: $(".searchCityDesktop"),
    titleCityDesktop: $(".titleCityDesktop__title"),
    dashBoardBtn: $(".navDesktop__dashBoardBtn"),
    savedCitiesBtn: $(".navDesktop__saveCityBtn"),
  },
  modals: {
    modalLoading: $(".modalLoading"),
    modalFirstLoading: $(".modalFirstLoading"),
    modalFail: $(".modalFail"),
    modalExceedPetitions: $(".modalExceedPetitions"),
    errorMessage: $(".citySearched"),
    closeModalFailed: $(".closeModalFail"),
  },
};
export default nodes;
